### ISSUE TITLE
pip install succeeds with python 3.5.2 but fails at runtime

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/docker-with-gitlab-secrets#3]
I see the docs say python >=3.6 is required, but pip doesn't seem to care. 

When installed by pip and run with python 3.5.2, docker-with-gitlab-secrets fails with a SyntaxError:
```
# docker-with-gitlab-secrets run -it mercury/taos bash
Traceback (most recent call last):
  File "/usr/local/bin/docker-with-gitlab-secrets", line 7, in <module>
    from dockerwithgitlabsecrets.entrypoint import main
  File "/usr/local/lib/python3.5/dist-packages/dockerwithgitlabsecrets/entrypoint.py", line 18
    DEFAULT_CONFIG_FILE = f"{os.path.expanduser('~')}/.dwgs-config.yml"
                                                                      ^
SyntaxError: invalid syntax
```

**Comment by colin-nolan** [comment]
Unfortunately, there is no way to state a minimum Python version in the setup. The work around appears to be to crudely detect a version issue before `setup` is ran:
https://stackoverflow.com/a/19535016/1348809
